title: Cameron Milne
logo: /assets/img/CMR.jpg
description: > #text below image
  <p align="center">
    <a href="https://www.linkedin.com/in/cameron-milne/">LinkedIn</a> |
    <a href="https://github.com/ccmilne">GitHub</a>
  </p>

  <p align="justify">
  Data Scientist with experience building data-intensive applications while delivering analytical solutions to improve decision-making.
  <br><br>
  Currently working for KPMG's Data, Analytics, and AI team. Industry sectors have included Life Sciences, Banking, and Entertainment.
  <br><br>
  </p>

#show_downloads: true
theme: jekyll-theme-minimal

plugins:
  - github-pages-octopress-toc:
      permalink: /
      title: "Table of Contents"
      css_class: "toc"