title: Cameron Milne
logo: /assets/img/CMR.jpg
description: > #text below image
  <p align="center">
    <a href="https://www.linkedin.com/in/cameron-milne/">LinkedIn</a> |
    <a href="https://github.com/ccmilne">GitHub</a>
  </p>

  <p align="justify">
  Data Scientist with experience building data-intensive applications while delivering analytical solutions to improve decision-making.
  <br><br>
  Formerly a Data Scientist on KPMG's Data, Analytics, and AI team working on projects in the Life Sciences, Banking, and Entertainment sectors.
  <br><br>
  </p>

theme: jekyll-theme-minimal
#show_downloads: true

# # Conversion
# markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false

# # Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

plugins:
  - jekyll-toc
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jekyll-include-cache
#   - jekyll-redirect-from

# # mimic GitHub Pages with --safe
# whitelist:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jekyll-include-cache